### ISSUE TITLE
Buttons pressed doesn't show up in counters.

### ISSUE THREAD

**Issue by Aikocho** [PiKeyAr/SDLJoystick#3]
I'll try to explain it as best as I can. Lets say I make a simple event: Any button pressed with the controller ID of 0, the action would be to set counter or set value to button pressed index or last button pressed.

However, every value that I get, no matter how I make the event or action, it just shows the index or numbers as -1 or 0.

**Comment by PiKeyAr** [comment]
This should be fixed with the latest release. I've also updated the example to test last button pressed/released.
The "held button index" expression returns the index of the button(s) being held at the moment, and the second value in the expression is the button slot, which depends on how many buttons are being held at the same time. For example,
`HeldButton( "SDL Joystick object", 0, 0 )` will return the index of the first held button (-1 if nothing is being held), while
`HeldButton( "SDL Joystick object", 0, 1 )` will return the second held button's index if you're holding two buttons or more (-1 if you're holding only one button or nothing).
