### ISSUE TITLE
Gamecube adapter causes problems [Release 1.65] [Windows 10]

### ISSUE THREAD

**Issue by tatedeterra** [PiKeyAr/SDLJoystick#8]
When a gamecube controller adapter is plugged in (with or without any controllers plugged into it), all controller slots will say they are a Nintendo GameCube Controller, and no other controllers will function.

If the gamecube adapter is plugged in AFTER the application has started the other controllers will still work, however all slots after it will show "Nintendo GameCube Controller", again, regardless of any actual controllers plugged in

The number of controller slots also jumps from 16 to 16 plus the number of other controllers plugged in. (though the controller slots after 16 are blank)

It seems that the gamecube controller adapter is hogging up an entire 16 controller slots according to SDL, however checking the game controllers in windows (joy.cpl) shows that the adapter only uses 4 slots. Its worth noting that all 4 controller slots are active whether there is a controller plugged into them or not.

In the screenshot, I have 2 controllers (that work otherwise) plugged in plus the gamecube adapter. All 16 slots show up as "Nintendo GameCube Controller", slots 17 and 18 dont show anything, and the other two controllers do not work.
![CTdebugger](https://github.com/PiKeyAr/SDLJoystick/assets/57497195/4228a457-f98f-44cc-bab3-9fdb841f0a8f)

**Comment by PiKeyAr** [comment]
This sounds like SDL's "device connected" events are fired multiple times. The adapter is probably doing something a regular controller wouldn't do. If SDL sees these events coming from the same device ID, this is probably fixable on the extension's side.

Slots above 15 not working is because the extension supports up to 16 controllers plugged in at the same time. Since SDL reports the number of devices correctly, I think that limit can be increased. I don't the maximum number of controllers SDL supports though.

Apart from the slots issue, does anything connected to this adapter (e.g. a Gamecube controller) work at all?

**Comment by PiKeyAr** [comment]
This sounds like SDL's "device connected" events are fired multiple times. The adapter is probably doing something a regular controller wouldn't do. If SDL sees these events coming from the same device ID, this is probably fixable on the extension's side.

Slots above 15 not working is because the extension supports up to 16 controllers plugged in at the same time. Since SDL reports the number of devices correctly, I think that limit can be increased. I don't know the maximum number of controllers SDL supports though.

Apart from the slots issue, does anything connected to this adapter (e.g. a Gamecube controller) work at all?

**Comment by tatedeterra** [comment]
Sounds plausible, thanks for looking into it
Any controllers plugged into the adapter still function properly, even after the issue occurs

**Comment by PiKeyAr** [comment]
Hi! Can you try with this test version? It increases the maximum number of controllers to 32 and checks for device ID duplicates when a new "device added" event is fired.
[ToInst.zip](https://github.com/PiKeyAr/SDLJoystick/files/12047726/ToInst.zip)

**Comment by PiKeyAr** [comment]
Hi! Can you try with this test version? It checks for duplicate device IDs when a new "device added" event fires, and increases the maximum number of controllers to 32.
[ToInst.zip](https://github.com/PiKeyAr/SDLJoystick/files/12047743/ToInst.zip)

**Comment by PiKeyAr** [comment]
Hi! Can you try with this test version? It checks for duplicate device IDs when a new "device added" event fires, and increases the maximum number of controllers to 32.
[ToInst.zip](https://github.com/PiKeyAr/SDLJoystick/files/12047793/ToInst.zip)

**Comment by tatedeterra** [comment]
that solved my issue, thank you!

**Comment by PiKeyAr** [comment]
Good to know. I'll make a new release soon.
